const apiKey = import.meta.env.VITE_API_KEY || '';
const baseUrl =
  import.meta.env.VITE_COUNTRY_BASE_URL || 'https://countryapi.io/api/all';

interface apiCountry {
  alpha2Code: string;
  alpha3Code: string;
  altSpellings: string[];
  area: number;
  borders: string[];
  callingCode: string;
  capital: string;
  cioc: string;
  currencies: Record<string, { name: string; symbol?: string }>;
  demonyms: Record<string, { f: string; m: string }>;
  flag: {
    small: string;
    medium: string;
    large: string;
  };
  gini: string;
  languages: Record<string, string>;
  latLng: {
    country: number[];
    capital: number[];
  };
  name: string;
  nativeNames: Record<string, { common: string; official: string }>;
  numericCode: string;
  official_name: string;
  population: number;
  region: string;
  regionalBlocs: Array<{
    name: string;
    acronym: string;
    otherNames?: string[];
  }>;
  subregion: string;
  timezones: string[];
  topLevelDomain: string[];
  translations: Record<string, string>;
}

const getCountries = async (): Promise<apiCountry[]> => {
  try {
    const headers: Record<string, string> = {
      Accept: 'application/json',
    };

    if (apiKey) {
      headers['Authorization'] = `Bearer ${apiKey}`;
    }

    const response = await fetch(baseUrl, {
      method: 'GET',
      headers,
    });

    if (!response.ok) {
      console.error(`HTTP error! status: ${response.status}`);
      throw new Error(`Failed to fetch countries: ${response.status}`);
    }

    const data = await response.json();

    return data;
  } catch (error) {
    console.error('Error fetching countries:', error);
    return [
      {
        alpha2Code: 'US',
        alpha3Code: 'USA',
        altSpellings: ['US', 'USA'],
        area: 9833517,
        borders: ['CAN', 'MEX'],
        callingCode: '+1',
        capital: 'Washington, D.C.',
        cioc: 'USA',
        currencies: { USD: { name: 'US Dollar' } },
        demonyms: { eng: { f: 'American', m: 'American' } },
        flag: { small: '🇺🇸', medium: '🇺🇸', large: '🇺🇸' },
        gini: '41.4',
        languages: { eng: 'English' },
        latLng: { country: [38, -97], capital: [38.8951, -77.0364] },
        name: 'United States',
        nativeNames: {
          eng: {
            common: 'United States',
            official: 'United States of America',
          },
        },
        numericCode: '840',
        official_name: 'United States of America',
        population: 331002651,
        region: 'Americas',
        regionalBlocs: [],
        subregion: 'North America',
        timezones: ['UTC-12:00'],
        topLevelDomain: ['.us'],
        translations: { eng: 'United States' },
      },
      {
        alpha2Code: 'CA',
        alpha3Code: 'CAN',
        altSpellings: ['CA', 'CAN'],
        area: 9984670,
        borders: ['USA'],
        callingCode: '+1',
        capital: 'Ottawa',
        cioc: 'CAN',
        currencies: { CAD: { name: 'Canadian Dollar' } },
        demonyms: { eng: { f: 'Canadian', m: 'Canadian' } },
        flag: { small: '🇨🇦', medium: '🇨🇦', large: '🇨🇦' },
        gini: '32.1',
        languages: { eng: 'English', fra: 'French' },
        latLng: { country: [60, -95], capital: [45.4215, -75.6972] },
        name: 'Canada',
        nativeNames: { eng: { common: 'Canada', official: 'Canada' } },
        numericCode: '124',
        official_name: 'Canada',
        population: 37742154,
        region: 'Americas',
        regionalBlocs: [],
        subregion: 'North America',
        timezones: ['UTC-08:00'],
        topLevelDomain: ['.ca'],
        translations: { eng: 'Canada' },
      },
      {
        alpha2Code: 'GB',
        alpha3Code: 'GBR',
        altSpellings: ['GB', 'UK'],
        area: 242900,
        borders: ['IRL'],
        callingCode: '+44',
        capital: 'London',
        cioc: 'GBR',
        currencies: { GBP: { name: 'British Pound' } },
        demonyms: { eng: { f: 'British', m: 'British' } },
        flag: { small: '🇬🇧', medium: '🇬🇧', large: '🇬🇧' },
        gini: '36.0',
        languages: { eng: 'English' },
        latLng: { country: [54, -2], capital: [51.5074, -0.1278] },
        name: 'United Kingdom',
        nativeNames: {
          eng: {
            common: 'United Kingdom',
            official: 'United Kingdom of Great Britain and Northern Ireland',
          },
        },
        numericCode: '826',
        official_name: 'United Kingdom of Great Britain and Northern Ireland',
        population: 67215293,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Northern Europe',
        timezones: ['UTC+00:00'],
        topLevelDomain: ['.uk'],
        translations: { eng: 'United Kingdom' },
      },
      {
        alpha2Code: 'DE',
        alpha3Code: 'DEU',
        altSpellings: ['DE', 'GER'],
        area: 357114,
        borders: [
          'AUT',
          'BEL',
          'CZE',
          'DNK',
          'FRA',
          'LUX',
          'NLD',
          'POL',
          'CHE',
        ],
        callingCode: '+49',
        capital: 'Berlin',
        cioc: 'GER',
        currencies: { EUR: { name: 'Euro' } },
        demonyms: { eng: { f: 'German', m: 'German' } },
        flag: { small: '🇩🇪', medium: '🇩🇪', large: '🇩🇪' },
        gini: '31.9',
        languages: { deu: 'German' },
        latLng: { country: [51, 9], capital: [52.52, 13.405] },
        name: 'Germany',
        nativeNames: {
          deu: {
            common: 'Deutschland',
            official: 'Bundesrepublik Deutschland',
          },
        },
        numericCode: '276',
        official_name: 'Federal Republic of Germany',
        population: 83190556,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Western Europe',
        timezones: ['UTC+01:00'],
        topLevelDomain: ['.de'],
        translations: { eng: 'Germany' },
      },
      {
        alpha2Code: 'FR',
        alpha3Code: 'FRA',
        altSpellings: ['FR', 'FRA'],
        area: 551695,
        borders: ['AND', 'BEL', 'DEU', 'ITA', 'LUX', 'MCO', 'ESP', 'CHE'],
        callingCode: '+33',
        capital: 'Paris',
        cioc: 'FRA',
        currencies: { EUR: { name: 'Euro' } },
        demonyms: { eng: { f: 'French', m: 'French' } },
        flag: { small: '🇫🇷', medium: '🇫🇷', large: '🇫🇷' },
        gini: '32.7',
        languages: { fra: 'French' },
        latLng: { country: [46, 2], capital: [48.8566, 2.3522] },
        name: 'France',
        nativeNames: { fra: { common: 'France', official: 'French Republic' } },
        numericCode: '250',
        official_name: 'French Republic',
        population: 67391582,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Western Europe',
        timezones: ['UTC+01:00'],
        topLevelDomain: ['.fr'],
        translations: { eng: 'France' },
      },
      {
        alpha2Code: 'JP',
        alpha3Code: 'JPN',
        altSpellings: ['JP', 'JPN'],
        area: 377930,
        borders: [],
        callingCode: '+81',
        capital: 'Tokyo',
        cioc: 'JPN',
        currencies: { JPY: { name: 'Japanese Yen' } },
        demonyms: { eng: { f: 'Japanese', m: 'Japanese' } },
        flag: { small: '🇯🇵', medium: '🇯🇵', large: '🇯🇵' },
        gini: '32.1',
        languages: { jpn: 'Japanese' },
        latLng: { country: [36, 138], capital: [35.6762, 139.6503] },
        name: 'Japan',
        nativeNames: { jpn: { common: '日本', official: '日本国' } },
        numericCode: '392',
        official_name: 'Japan',
        population: 125836021,
        region: 'Asia',
        regionalBlocs: [],
        subregion: 'Eastern Asia',
        timezones: ['UTC+09:00'],
        topLevelDomain: ['.jp'],
        translations: { eng: 'Japan' },
      },
      {
        alpha2Code: 'AU',
        alpha3Code: 'AUS',
        altSpellings: ['AU', 'AUS'],
        area: 7692024,
        borders: [],
        callingCode: '+61',
        capital: 'Canberra',
        cioc: 'AUS',
        currencies: { AUD: { name: 'Australian Dollar' } },
        demonyms: { eng: { f: 'Australian', m: 'Australian' } },
        flag: { small: '🇦🇺', medium: '🇦🇺', large: '🇦🇺' },
        gini: '34.4',
        languages: { eng: 'English' },
        latLng: { country: [-27, 133], capital: [-35.2809, 149.13] },
        name: 'Australia',
        nativeNames: {
          eng: { common: 'Australia', official: 'Commonwealth of Australia' },
        },
        numericCode: '036',
        official_name: 'Commonwealth of Australia',
        population: 25499884,
        region: 'Oceania',
        regionalBlocs: [],
        subregion: 'Australia and New Zealand',
        timezones: ['UTC+05:00'],
        topLevelDomain: ['.au'],
        translations: { eng: 'Australia' },
      },
      {
        alpha2Code: 'BR',
        alpha3Code: 'BRA',
        altSpellings: ['BR', 'BRA'],
        area: 8515767,
        borders: [
          'ARG',
          'BOL',
          'COL',
          'GUF',
          'GUY',
          'PRY',
          'PER',
          'SUR',
          'URY',
          'VEN',
        ],
        callingCode: '+55',
        capital: 'Brasília',
        cioc: 'BRA',
        currencies: { BRL: { name: 'Brazilian Real' } },
        demonyms: { eng: { f: 'Brazilian', m: 'Brazilian' } },
        flag: { small: '🇧🇷', medium: '🇧🇷', large: '🇧🇷' },
        gini: '53.9',
        languages: { por: 'Portuguese' },
        latLng: { country: [-10, -55], capital: [-15.7942, -47.8822] },
        name: 'Brazil',
        nativeNames: {
          por: { common: 'Brasil', official: 'Federative Republic of Brazil' },
        },
        numericCode: '076',
        official_name: 'Federative Republic of Brazil',
        population: 212559417,
        region: 'Americas',
        regionalBlocs: [],
        subregion: 'South America',
        timezones: ['UTC-05:00'],
        topLevelDomain: ['.br'],
        translations: { eng: 'Brazil' },
      },
      {
        alpha2Code: 'IN',
        alpha3Code: 'IND',
        altSpellings: ['IN', 'IND'],
        area: 3287590,
        borders: ['AFG', 'BGD', 'BTN', 'MMR', 'CHN', 'NPL', 'PAK', 'LKA'],
        callingCode: '+91',
        capital: 'New Delhi',
        cioc: 'IND',
        currencies: { INR: { name: 'Indian Rupee' } },
        demonyms: { eng: { f: 'Indian', m: 'Indian' } },
        flag: { small: '🇮🇳', medium: '🇮🇳', large: '🇮🇳' },
        gini: '35.7',
        languages: { eng: 'English', hin: 'Hindi' },
        latLng: { country: [20, 77], capital: [28.6139, 77.209] },
        name: 'India',
        nativeNames: {
          eng: { common: 'India', official: 'Republic of India' },
        },
        numericCode: '356',
        official_name: 'Republic of India',
        population: 1380004385,
        region: 'Asia',
        regionalBlocs: [],
        subregion: 'Southern Asia',
        timezones: ['UTC+05:30'],
        topLevelDomain: ['.in'],
        translations: { eng: 'India' },
      },
      {
        alpha2Code: 'CN',
        alpha3Code: 'CHN',
        altSpellings: ['CN', 'CHN'],
        area: 9596961,
        borders: [
          'AFG',
          'BTN',
          'MMR',
          'HKG',
          'IND',
          'KAZ',
          'PRK',
          'KGZ',
          'LAO',
          'MAC',
          'MNG',
          'PAK',
          'RUS',
          'TJK',
          'VNM',
        ],
        callingCode: '+86',
        capital: 'Beijing',
        cioc: 'CHN',
        currencies: { CNY: { name: 'Chinese Yuan' } },
        demonyms: { eng: { f: 'Chinese', m: 'Chinese' } },
        flag: { small: '🇨🇳', medium: '🇨🇳', large: '🇨🇳' },
        gini: '38.5',
        languages: { zho: 'Chinese' },
        latLng: { country: [35, 105], capital: [39.9042, 116.4074] },
        name: 'China',
        nativeNames: {
          zho: { common: '中国', official: "People's Republic of China" },
        },
        numericCode: '156',
        official_name: "People's Republic of China",
        population: 1439323776,
        region: 'Asia',
        regionalBlocs: [],
        subregion: 'Eastern Asia',
        timezones: ['UTC+08:00'],
        topLevelDomain: ['.cn'],
        translations: { eng: 'China' },
      },
      {
        alpha2Code: 'IT',
        alpha3Code: 'ITA',
        altSpellings: ['IT', 'ITA'],
        area: 301336,
        borders: ['AUT', 'FRA', 'SMR', 'SVN', 'CHE', 'VAT'],
        callingCode: '+39',
        capital: 'Rome',
        cioc: 'ITA',
        currencies: { EUR: { name: 'Euro' } },
        demonyms: { eng: { f: 'Italian', m: 'Italian' } },
        flag: { small: '🇮🇹', medium: '🇮🇹', large: '🇮🇹' },
        gini: '36.0',
        languages: { ita: 'Italian' },
        latLng: { country: [42.8333, 12.8333], capital: [41.9028, 12.4964] },
        name: 'Italy',
        nativeNames: {
          ita: { common: 'Italia', official: 'Italian Republic' },
        },
        numericCode: '380',
        official_name: 'Italian Republic',
        population: 60461826,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Southern Europe',
        timezones: ['UTC+01:00'],
        topLevelDomain: ['.it'],
        translations: { eng: 'Italy' },
      },
      {
        alpha2Code: 'ES',
        alpha3Code: 'ESP',
        altSpellings: ['ES', 'ESP'],
        area: 505990,
        borders: ['AND', 'FRA', 'GIB', 'PRT', 'MAR'],
        callingCode: '+34',
        capital: 'Madrid',
        cioc: 'ESP',
        currencies: { EUR: { name: 'Euro' } },
        demonyms: { eng: { f: 'Spanish', m: 'Spanish' } },
        flag: { small: '🇪🇸', medium: '🇪🇸', large: '🇪🇸' },
        gini: '34.7',
        languages: { spa: 'Spanish' },
        latLng: { country: [40, -4], capital: [40.4168, -3.7038] },
        name: 'Spain',
        nativeNames: {
          spa: { common: 'España', official: 'Kingdom of Spain' },
        },
        numericCode: '724',
        official_name: 'Kingdom of Spain',
        population: 46754778,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Southern Europe',
        timezones: ['UTC+01:00'],
        topLevelDomain: ['.es'],
        translations: { eng: 'Spain' },
      },
      {
        alpha2Code: 'NL',
        alpha3Code: 'NLD',
        altSpellings: ['NL', 'NLD'],
        area: 41850,
        borders: ['BEL', 'DEU'],
        callingCode: '+31',
        capital: 'Amsterdam',
        cioc: 'NED',
        currencies: { EUR: { name: 'Euro' } },
        demonyms: { eng: { f: 'Dutch', m: 'Dutch' } },
        flag: { small: '🇳🇱', medium: '🇳🇱', large: '🇳🇱' },
        gini: '28.1',
        languages: { nld: 'Dutch' },
        latLng: { country: [52.5, 5.75], capital: [52.3676, 4.9041] },
        name: 'Netherlands',
        nativeNames: {
          nld: { common: 'Nederland', official: 'Kingdom of the Netherlands' },
        },
        numericCode: '528',
        official_name: 'Kingdom of the Netherlands',
        population: 17134872,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Western Europe',
        timezones: ['UTC+01:00'],
        topLevelDomain: ['.nl'],
        translations: { eng: 'Netherlands' },
      },
      {
        alpha2Code: 'SE',
        alpha3Code: 'SWE',
        altSpellings: ['SE', 'SWE'],
        area: 450295,
        borders: ['FIN', 'NOR'],
        callingCode: '+46',
        capital: 'Stockholm',
        cioc: 'SWE',
        currencies: { SEK: { name: 'Swedish Krona' } },
        demonyms: { eng: { f: 'Swedish', m: 'Swedish' } },
        flag: { small: '🇸🇪', medium: '🇸🇪', large: '🇸🇪' },
        gini: '27.6',
        languages: { swe: 'Swedish' },
        latLng: { country: [62, 15], capital: [59.3293, 18.0686] },
        name: 'Sweden',
        nativeNames: {
          swe: { common: 'Sverige', official: 'Kingdom of Sweden' },
        },
        numericCode: '752',
        official_name: 'Kingdom of Sweden',
        population: 10099265,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Northern Europe',
        timezones: ['UTC+01:00'],
        topLevelDomain: ['.se'],
        translations: { eng: 'Sweden' },
      },
      {
        alpha2Code: 'NO',
        alpha3Code: 'NOR',
        altSpellings: ['NO', 'NOR'],
        area: 323802,
        borders: ['FIN', 'SWE', 'RUS'],
        callingCode: '+47',
        capital: 'Oslo',
        cioc: 'NOR',
        currencies: { NOK: { name: 'Norwegian Krone' } },
        demonyms: { eng: { f: 'Norwegian', m: 'Norwegian' } },
        flag: { small: '🇳🇴', medium: '🇳🇴', large: '🇳🇴' },
        gini: '27.5',
        languages: { nor: 'Norwegian' },
        latLng: { country: [62, 10], capital: [59.9139, 10.7522] },
        name: 'Norway',
        nativeNames: {
          nor: { common: 'Norge', official: 'Kingdom of Norway' },
        },
        numericCode: '578',
        official_name: 'Kingdom of Norway',
        population: 5421241,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Northern Europe',
        timezones: ['UTC+01:00'],
        topLevelDomain: ['.no'],
        translations: { eng: 'Norway' },
      },
      {
        alpha2Code: 'DK',
        alpha3Code: 'DNK',
        altSpellings: ['DK', 'DNK'],
        area: 43094,
        borders: ['DEU'],
        callingCode: '+45',
        capital: 'Copenhagen',
        cioc: 'DEN',
        currencies: { DKK: { name: 'Danish Krone' } },
        demonyms: { eng: { f: 'Danish', m: 'Danish' } },
        flag: { small: '🇩🇰', medium: '🇩🇰', large: '🇩🇰' },
        gini: '27.7',
        languages: { dan: 'Danish' },
        latLng: { country: [56, 10], capital: [55.6761, 12.5683] },
        name: 'Denmark',
        nativeNames: {
          dan: { common: 'Danmark', official: 'Kingdom of Denmark' },
        },
        numericCode: '208',
        official_name: 'Kingdom of Denmark',
        population: 5792202,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Northern Europe',
        timezones: ['UTC+01:00'],
        topLevelDomain: ['.dk'],
        translations: { eng: 'Denmark' },
      },
      {
        alpha2Code: 'CH',
        alpha3Code: 'CHE',
        altSpellings: ['CH', 'CHE'],
        area: 41284,
        borders: ['AUT', 'FRA', 'DEU', 'ITA', 'LIE'],
        callingCode: '+41',
        capital: 'Bern',
        cioc: 'SUI',
        currencies: { CHF: { name: 'Swiss Franc' } },
        demonyms: { eng: { f: 'Swiss', m: 'Swiss' } },
        flag: { small: '🇨🇭', medium: '🇨🇭', large: '🇨🇭' },
        gini: '32.7',
        languages: { deu: 'German', fra: 'French', ita: 'Italian' },
        latLng: { country: [47, 8], capital: [46.9479, 7.4474] },
        name: 'Switzerland',
        nativeNames: {
          deu: { common: 'Schweiz', official: 'Swiss Confederation' },
        },
        numericCode: '756',
        official_name: 'Swiss Confederation',
        population: 8654622,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Western Europe',
        timezones: ['UTC+01:00'],
        topLevelDomain: ['.ch'],
        translations: { eng: 'Switzerland' },
      },
      {
        alpha2Code: 'AT',
        alpha3Code: 'AUT',
        altSpellings: ['AT', 'AUT'],
        area: 83871,
        borders: ['CZE', 'DEU', 'HUN', 'ITA', 'LIE', 'SVK', 'SVN', 'CHE'],
        callingCode: '+43',
        capital: 'Vienna',
        cioc: 'AUT',
        currencies: { EUR: { name: 'Euro' } },
        demonyms: { eng: { f: 'Austrian', m: 'Austrian' } },
        flag: { small: '🇦🇹', medium: '🇦🇹', large: '🇦🇹' },
        gini: '30.5',
        languages: { deu: 'German' },
        latLng: { country: [47.3333, 13.3333], capital: [48.2082, 16.3738] },
        name: 'Austria',
        nativeNames: {
          deu: { common: 'Österreich', official: 'Republic of Austria' },
        },
        numericCode: '040',
        official_name: 'Republic of Austria',
        population: 9006398,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Central Europe',
        timezones: ['UTC+01:00'],
        topLevelDomain: ['.at'],
        translations: { eng: 'Austria' },
      },
      {
        alpha2Code: 'BE',
        alpha3Code: 'BEL',
        altSpellings: ['BE', 'BEL'],
        area: 30528,
        borders: ['FRA', 'DEU', 'LUX', 'NLD'],
        callingCode: '+32',
        capital: 'Brussels',
        cioc: 'BEL',
        currencies: { EUR: { name: 'Euro' } },
        demonyms: { eng: { f: 'Belgian', m: 'Belgian' } },
        flag: { small: '🇧🇪', medium: '🇧🇪', large: '🇧🇪' },
        gini: '27.2',
        languages: { deu: 'German', fra: 'French', nld: 'Dutch' },
        latLng: { country: [50.8333, 4], capital: [50.8503, 4.3517] },
        name: 'Belgium',
        nativeNames: {
          deu: { common: 'Belgien', official: 'Kingdom of Belgium' },
        },
        numericCode: '056',
        official_name: 'Kingdom of Belgium',
        population: 11589623,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Western Europe',
        timezones: ['UTC+01:00'],
        topLevelDomain: ['.be'],
        translations: { eng: 'Belgium' },
      },
      {
        alpha2Code: 'HR',
        alpha3Code: 'HRV',
        altSpellings: ['HR', 'HRV'],
        area: 56594,
        borders: ['BIH', 'HUN', 'MNE', 'SRB', 'SVN'],
        callingCode: '+385',
        capital: 'Zagreb',
        cioc: 'CRO',
        currencies: { EUR: { name: 'Euro' } },
        demonyms: { eng: { f: 'Croatian', m: 'Croatian' } },
        flag: { small: '🇭🇷', medium: '🇭🇷', large: '🇭🇷' },
        gini: '29.7',
        languages: { hrv: 'Croatian' },
        latLng: { country: [45.1667, 15.5], capital: [45.815, 15.9819] },
        name: 'Croatia',
        nativeNames: {
          hrv: { common: 'Hrvatska', official: 'Republic of Croatia' },
        },
        numericCode: '191',
        official_name: 'Republic of Croatia',
        population: 4047200,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Southern Europe',
        timezones: ['UTC+01:00'],
        topLevelDomain: ['.hr'],
        translations: { eng: 'Croatia' },
      },
      {
        alpha2Code: 'BY',
        alpha3Code: 'BLR',
        altSpellings: ['BY', 'BLR'],
        area: 207600,
        borders: ['LVA', 'LTU', 'POL', 'RUS', 'UKR'],
        callingCode: '+375',
        capital: 'Minsk',
        cioc: 'BLR',
        currencies: { BYN: { name: 'Belarusian Ruble' } },
        demonyms: { eng: { f: 'Belarusian', m: 'Belarusian' } },
        flag: { small: '🇧🇾', medium: '🇧🇾', large: '🇧🇾' },
        gini: '25.3',
        languages: { bel: 'Belarusian', rus: 'Russian' },
        latLng: { country: [53, 28], capital: [53.9045, 27.5615] },
        name: 'Belarus',
        nativeNames: {
          bel: { common: 'Беларусь', official: 'Republic of Belarus' },
        },
        numericCode: '112',
        official_name: 'Republic of Belarus',
        population: 9449323,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Eastern Europe',
        timezones: ['UTC+03:00'],
        topLevelDomain: ['.by'],
        translations: { eng: 'Belarus' },
      },
      {
        alpha2Code: 'UA',
        alpha3Code: 'UKR',
        altSpellings: ['UA', 'UKR'],
        area: 603550,
        borders: ['BLR', 'HUN', 'MDA', 'POL', 'ROU', 'RUS', 'SVK'],
        callingCode: '+380',
        capital: 'Kyiv',
        cioc: 'UKR',
        currencies: { UAH: { name: 'Ukrainian Hryvnia' } },
        demonyms: { eng: { f: 'Ukrainian', m: 'Ukrainian' } },
        flag: { small: '🇺🇦', medium: '🇺🇦', large: '🇺🇦' },
        gini: '26.1',
        languages: { ukr: 'Ukrainian' },
        latLng: { country: [49, 32], capital: [50.4501, 30.5234] },
        name: 'Ukraine',
        nativeNames: { ukr: { common: 'Україна', official: 'Ukraine' } },
        numericCode: '804',
        official_name: 'Ukraine',
        population: 44134693,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Eastern Europe',
        timezones: ['UTC+02:00'],
        topLevelDomain: ['.ua'],
        translations: { eng: 'Ukraine' },
      },
      {
        alpha2Code: 'PL',
        alpha3Code: 'POL',
        altSpellings: ['PL', 'POL'],
        area: 312679,
        borders: ['BLR', 'CZE', 'DEU', 'LTU', 'RUS', 'SVK', 'UKR'],
        callingCode: '+48',
        capital: 'Warsaw',
        cioc: 'POL',
        currencies: { PLN: { name: 'Polish Złoty' } },
        demonyms: { eng: { f: 'Polish', m: 'Polish' } },
        flag: { small: '🇵🇱', medium: '🇵🇱', large: '🇵🇱' },
        gini: '30.2',
        languages: { pol: 'Polish' },
        latLng: { country: [52, 20], capital: [52.2297, 21.0122] },
        name: 'Poland',
        nativeNames: {
          pol: { common: 'Polska', official: 'Republic of Poland' },
        },
        numericCode: '616',
        official_name: 'Republic of Poland',
        population: 37846611,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Central Europe',
        timezones: ['UTC+01:00'],
        topLevelDomain: ['.pl'],
        translations: { eng: 'Poland' },
      },
      {
        alpha2Code: 'LT',
        alpha3Code: 'LTU',
        altSpellings: ['LT', 'LTU'],
        area: 65300,
        borders: ['BLR', 'LVA', 'POL', 'RUS'],
        callingCode: '+370',
        capital: 'Vilnius',
        cioc: 'LTU',
        currencies: { EUR: { name: 'Euro' } },
        demonyms: { eng: { f: 'Lithuanian', m: 'Lithuanian' } },
        flag: { small: '🇱🇹', medium: '🇱🇹', large: '🇱🇹' },
        gini: '35.7',
        languages: { lit: 'Lithuanian' },
        latLng: { country: [56, 24], capital: [54.6872, 25.2797] },
        name: 'Lithuania',
        nativeNames: {
          lit: { common: 'Lietuva', official: 'Republic of Lithuania' },
        },
        numericCode: '440',
        official_name: 'Republic of Lithuania',
        population: 2722289,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Northern Europe',
        timezones: ['UTC+02:00'],
        topLevelDomain: ['.lt'],
        translations: { eng: 'Lithuania' },
      },
      {
        alpha2Code: 'LV',
        alpha3Code: 'LVA',
        altSpellings: ['LV', 'LVA'],
        area: 64559,
        borders: ['BLR', 'EST', 'LTU', 'RUS'],
        callingCode: '+371',
        capital: 'Riga',
        cioc: 'LAT',
        currencies: { EUR: { name: 'Euro' } },
        demonyms: { eng: { f: 'Latvian', m: 'Latvian' } },
        flag: { small: '🇱🇻', medium: '🇱🇻', large: '🇱🇻' },
        gini: '35.1',
        languages: { lav: 'Latvian' },
        latLng: { country: [57, 25], capital: [56.9496, 24.1052] },
        name: 'Latvia',
        nativeNames: {
          lav: { common: 'Latvija', official: 'Republic of Latvia' },
        },
        numericCode: '428',
        official_name: 'Republic of Latvia',
        population: 1901548,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Northern Europe',
        timezones: ['UTC+02:00'],
        topLevelDomain: ['.lv'],
        translations: { eng: 'Latvia' },
      },
      {
        alpha2Code: 'EE',
        alpha3Code: 'EST',
        altSpellings: ['EE', 'EST'],
        area: 45227,
        borders: ['LVA', 'RUS'],
        callingCode: '+372',
        capital: 'Tallinn',
        cioc: 'EST',
        currencies: { EUR: { name: 'Euro' } },
        demonyms: { eng: { f: 'Estonian', m: 'Estonian' } },
        flag: { small: '🇪🇪', medium: '🇪🇪', large: '🇪🇪' },
        gini: '30.3',
        languages: { est: 'Estonian' },
        latLng: { country: [59, 26], capital: [59.4369, 24.7536] },
        name: 'Estonia',
        nativeNames: {
          est: { common: 'Eesti', official: 'Republic of Estonia' },
        },
        numericCode: '233',
        official_name: 'Republic of Estonia',
        population: 1326535,
        region: 'Europe',
        regionalBlocs: [],
        subregion: 'Northern Europe',
        timezones: ['UTC+02:00'],
        topLevelDomain: ['.ee'],
        translations: { eng: 'Estonia' },
      },
    ];
  }
};

export { getCountries, type apiCountry };
